apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-online
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-online.1.6.1
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
