apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

namespace: amq-online-infra


resources:
  - namespace.yaml
  - cluster-role-binding.yaml
  - amq-online-operatorgroup.yaml
  - amq-online-subscription.yaml
  - example-plans/*.yaml
  - example-roles/*.yaml
  - example-authservices/standard-authservice.yaml
 # - amq-online-subscription-infra.yaml
