:source-highlighter: highlightjs
:data-uri:
:toc: left
:markup-in-source: +verbatim,+quotes,+specialcharacters
:icons: font
:stylesdir: stylesheets
:stylesheet: colony.css

= AMQ Online

.*Goals*

. Deploy AMQ Online Operator
. Create a Sample Tenant enviroment
. Storage deployment OCP4 and specifically AMQ
. AMQ authentication service does not seems to be working with an (external) database
. Monitor AMQ Online Health



.*References:*
** https://enmasse.io/documentation/0.33.0/openshift.html[]
** https://access.redhat.com/documentation/en-us/red_hat_amq/7.7/html/installing_and_managing_amq_online_on_openshift/index[]
** https://access.redhat.com/documentation/en-us/red_hat_amq/7.7/html/using_amq_online_on_openshift/index[]


.*Background:*
In this blog entry we cover deploying the AMQ Online as well as other common tasks like Tenant namespace using GitOps, specifically in this case with ArgoCD. This blog post is going to assume some familiarity with AMQ Online and ArgoCD, and will concentrate on the more challenging aspects of using GitOps to deploy everything.

:sectnums:

== Define ArgoCD AppProject and Application

We defined project for AMQ Online which will cover amq-online "infra" components
Which are the following;

. AMQ Online operator
. Postgres operator
. Postgres Instance (will be used for AMQ Online AuthService)
. AMQ Online Monitoring

Refer to following file for full details

* xref:argocd-amq-online-config/amq-online-infra.yaml[argocd-amq-online-config/amq-online-infra.yaml]
* xref:argocd-amq-online-config/amq-online-project.yaml[argocd-amq-online-config/amq-online-project.yaml]

Apply the following to define the ArgoCD AppProject and Application
[source,bash]
----
oc apply -f argocd-amq-online-config
----
== Deploy AMQ Online Operator using ArgoCD
Deploying AMQ Online Operator is pretty straight forward. we will use the Operator Lifecycle Manager (OLM) , with OLM you define the Subscription and OperatorGroup and asynchronously OLM will install and deploy the operator.
