apiVersion: crunchydata.com/v1
kind: Pgreplica
metadata:
  labels:
    name:  dev-amq-online-rpl1
    pg-cluster:  dev-amq-online
    pgouser: admin
  name: amq-online-rpl1
  namespace: pgo
spec:
  clustername:  dev-amq-online
  name:  dev-amq-online-rpl1
  namespace: pgo
  replicastorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name:  dev-amq-online-rpl1
    size: 2G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  userlabels:
    NodeLabelKey: ""
    NodeLabelValue: ""
    crunchy-postgres-exporter: "false"
    pg-pod-anti-affinity: ""
    pgo-version: 4.5.1
