apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-monitoring
  namespace: argocd
spec:
  project: quay-config
  source:
    repoURL: https://github.com/Alliander/ot-quay-gitops.git
    targetRevision: HEAD
    path: base/quay-monitoring
  syncPolicy:
    automated:
      prune: true
# changes that are made to the live cluster will trigger automated sync
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: quay-enterprise
