apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-online-operator
  namespace: argocd
spec:
  project: amq-online
  source:
    repoURL: https://github.com/Alliander/ot-quay-gitops.git
    targetRevision: HEAD
    path: overlays/amq-online-instance/development
  syncPolicy:
    automated:
      prune: true
# changes that are made to the live cluster will trigger automated sync
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: amq-sample-tenant