apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: default-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    configSecretName: quay-config-app
    deploymentStrategy: RollingUpdate
    skipSetup: false
    enableStorageReplication: false
    replicas: 1
    externalAccess:
      hostname: quay-enterprise.apps.dummy
      tls:
        termination: edge
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
    database:
      volumeSize: 10Gi
      credentialsSecretName: db-quay-credentials
    resources:
      requests:
        memory: 4000Mi
      limits:
        memory: 8000Mi
    securityContext:
      fsGroup: 1001
    envVars:
      - name: DEBUGLOG
        value: "true"
  redis:
    credentialsSecretName: redis-credentials
    imagePullSecretName: redhat-pull-secret
  clair:
    enabled: true
    replicas: 1
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"
    database:
      credentialsSecretName: db-clair-credentials
