apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: amq-online-infra

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

# A user needs to be created on postgresql
# pgo create user --username=admin dev-amq-online --password passw0rd -n pgo
secretGenerator:
- name: db-creds
  literals:
   - database-user=admin
   - database-password=passw0rd
  type: Opaque

bases:
- ../../../base/amq-online-operator/

resources:
- db-authservice.yaml
