apiVersion: crunchydata.com/v1
kind: Pgreplica
metadata:
  labels:
    name: amq-online-rpl1
    pg-cluster: amq-online
    pgouser: admin
  name: amq-online-rpl1
  namespace: pgo
spec:
  clustername: amq-online
  name: amq-online-rpl1
  namespace: pgo
  replicastorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: amq-online-rpl1
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  userlabels:
    NodeLabelKey: ""
    NodeLabelValue: ""
    crunchy-postgres-exporter: "false"
    pg-pod-anti-affinity: ""
    pgo-version: 4.5.0
