apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: amq-online
  labels:
    autofail: "true"
    crunchy-pgbadger: "false"
    crunchy-pgha-scope: amq-online
    crunchy-postgres-exporter: "false"
    deployment-name: amq-online
    name: amq-online
    pg-cluster: amq-online
    pg-pod-anti-affinity: ""
    pgo-backrest: "true"
    pgo-version: 4.5.1
    pgouser: admin
  name: amq-online
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: amq-online
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  annotations:
    global:
      favorite: ""
    backrest:
      chair: ""
    pgBouncer:
      pool: ""
    postgres:
      elephant: ""
  backrestLimits: {}
  backrestRepoPath: ""
  backrestResources:
    memory: 48Mi
  backrestS3Bucket: ""
  backrestS3Endpoint: ""
  backrestS3Region: ""
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: ""
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos7-12.5-4.5.1
  clustername: amq-online
  customconfig: ""
  database: amq-online
  exporterport: "9187"
  limits: {}
  name: amq-online
  namespace: pgo
  pgBouncer:
    limits: {}
    replicas: 0
    resources:
      memory: "0"
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  policies: ""
  port: "5432"
  primarysecretname: amq-online-primaryuser-secret
  replicas: "0"
  rootsecretname: amq-online-postgres-secret
  shutdown: false
  standby: false
  tablespaceMounts: {}
  tls:
    caSecret: ""
    replicationTLSSecret: ""
    tlsSecret: ""
  tlsOnly: false
  user: amq-online
  userlabels:
    crunchy-postgres-exporter: "false"
    pg-pod-anti-affinity: ""
    pgo-version: 4.5.1
  usersecretname: amq-online-amq-online-secret