kind: Secret
apiVersion: v1
metadata:
  name: pgorole-pgoadmin
  labels:
    pgo-pgorole: 'true'
    rolename: pgoadmin
    vendor: crunchydata
data:
  permissions: Kg==
  rolename: cGdvYWRtaW4=
type: Opaque
