apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    name: postgres-operator
    vendor: crunchydata
  sessionAffinity: None
  type: LoadBalancer
