apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-online-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: amq-online
  source:
    repoURL: https://github.com/rahmed-rh/amq-online-gitops
    targetRevision: HEAD
    path: base/amq-online-config
  syncPolicy:
    automated:
      prune: true
# changes that are made to the live cluster will trigger automated sync
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: amq-online-infra
