apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: quay-operator
  name: quay-service-metrics
  namespace: quay-enterprise
spec:
  endpoints:
  - interval: 25s
    scheme: http
#    targetPort: 9091
    port: metrics
#    path: /health/instance
  selector:
    matchLabels:
        app: quay-operator
        quay-enterprise-component: app
